### PR TITLE
11358 add multiselect as an element extend dropdown element

### PR DESCRIPTION
**Pull request by andrei-kucherov**

### CODE REVIEW

**Comment by andrei-kucherov** [comment]
image

**Comment by propakov** [comment]
@andrei-kucherov on designs I see it looks a bit different (i mean little gray box for selected elements)
https://www.figma.com/file/oZnERMABuwJdO0pjZmj9qS/Bivariate-manager?node-id=4689%3A96160

**Comment by andrei-kucherov** [comment]
I've made it more generic, there is a specific function that is resposible how agreagated value will look like. I've done it for a purpose to support different behaviors in multiselect. Will add an example how to achieve ui pattern that u have shown above using such approach

**Comment by propakov** [comment]
good job! 👍

**Review by propakov — APPROVED** [review]

**Pull request merged**
